FROM jenkins/jenkins:2.513-jdk21

# Skip initial setup wizard
# ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

# Run as root to install additional packages if needed later
# USER root

# Switch back to jenkins user
USER jenkins

# Expose default Jenkins port & agent port
EXPOSE 8080 50000