FROM jenkins/jenkins:2.513-jdk21

ARG DOCKER_GID

USER root

COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

RUN groupadd -g ${DOCKER_GID} docker && usermod -aG docker jenkins

USER jenkins

EXPOSE 8080 50000